version: '3.9'

services:
    futions.api:
        image: ${DOCKER_REGISTRY-}futionscrmapipresentation
        container_name: Futions.Api
        build:
            context: .
            dockerfile: src/API/Futions.CRM.API.Presentation/Dockerfile
        ports:
            - 5000:8080
            - 5001:8081
        environment:
            ConnectionStrings__Database: "Server=Futions.Database;Database=ModularMonolith;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"

    futions.database:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: Futions.Database
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "YourStrong!Passw0rd"
            ACCEPT_EULA: "Y"
        volumes:
            - mssql_data:/var/opt/mssql

    futions.seq:
        image: datalust/seq:latest
        container_name: Futions.Seq
        ports:
            - "5341:5341"
            - "8081:80"
        environment:
            SEQ_FIRSTRUN_ADMINPASSWORD: "YourStrongPassword!"
            ACCEPT_EULA: "Y"

    futions.identity:
        image: quay.io/keycloak/keycloak:latest
        container_name: Futions.Identity
        command: start-dev #--import-realm
        environment:
            - KC_HEALTH_ENABLED=true
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        volumes:
            #- keycloak_data:/opt/keycloak/data
            #- keycloak_import:/opt/keycloak/data/import
            - ./.containers/identity:/opt/keycloak/data
            - ./.files:/opt/keycloak/data/import
        ports:
            - 18080:8080

volumes:
    mssql_data:
    #keycloak_data:
    #keycloak_import:
       

